config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'chatroom#index'
  post 'text', to: 'texts#create'
  mount ActionCable.server, at: '/cable'

  # sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # users log in 
  get 'signup', to: 'users#new'
  resources :users, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

# appllication model class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text.rb
# frozen_string_literal: true

class Text < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }, uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :texts
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# appication controller class
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to perform that action'
    redirect_to login_path
  end

  def logged_in_redirect
    return unless logged_in?

    flash[:error] = 'You are already logged in'
    redirect_to root_path
  end
  
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

# chatroom controller class
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @text = Text.new
    @texts = Text.custom_display
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# session controller class
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :require_user

  def create
    text = current_user.texts.build(text_params)
    if text.save
      ActionCable.server.broadcast "chatroom_channel", {mod_message: message_render(text)}
      
    end
  end

  private

  def text_params
    params.require(:text).permit(:body)
  end

  def message_render(text)
    render(partial: 'text', locals: {text: text})
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller class
class UsersController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Message #{@user.username}, you have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

# helper module
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>


<div class="ui fluid raised card chatbox">
  <div class="content" id="messages">
    <div class="ui feed" id="message-container">
        <%= render @texts %>
    </div>
  </div>
  <div class="extra content">
  <%= form_for(@text, html: {class: "ui reply form", role: "form"}, url: text_path, remote: true) do |f| %>
      <div class="field">
        <div class="ui fluid icon input">
          <%= f.text_field :body %>
          <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>

<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item" %>
        <%= link_to "Sign up", signup_path, class: "item" %>
      <% end %>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="item">
      <%= link_to "Log in", login_path, class: "ui primary button" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Message</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/texts/_text.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= text.user.username %></em>: <%= text.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Sign up
</h4>

<% if @user.errors.any? %>
  <div class="ui error message transition">
    <i class="close icon"></i>
    <div class="header">
      <h4>The following errors prevented the user from being saved</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="ui placeholder segment">
  <%= form_with(model: @user, html: {class: "ui form", role: "form"}, local: true) do |f| %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, placeholder: "Enter a username" %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Choose a password" %>
    </div>
      <%= f.submit "Sign up" , class: "ui orange submit button"  %>
  <% end %>
</div>